services:
  db:
    container_name: my_postgres
    image: postgres:16
    environment:
      POSTGRES_DB: "saaaw"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:    
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
